import {
      AC ,
      AD ,
      AE ,
      AF ,
      AG ,
      AI ,
      AL ,
      AM ,
      AO ,
      AQ ,
      AR ,
      AS ,
      AT ,
      AU ,
      AW ,
      AX ,
      AZ ,
      BA ,
      BB ,
      BD ,
      BE ,
      BF ,
      BG ,
      BH ,
      BI ,
      BJ ,
      BL ,
      BM ,
      BN ,
      BO ,
      BQ ,
      BR ,
      BS ,
      BT ,
      BV ,
      BW ,
      BY ,
      BZ ,
      CA ,
      CC ,
      CD ,
      CF ,
      CG ,
      CH ,
      CI ,
      CK ,
      CL ,
      CM ,
      CN ,
      CO ,
      CR ,
      CU ,
      CV ,
      CW ,
      CX ,
      CY ,
      CZ ,
      DE ,
      DJ ,
      DK ,
      DM ,
      DO ,
      DZ ,
      EC ,
      EE ,
      EG ,
      EH ,
      ER ,
      ES ,
      ET ,
      EU ,
      FI ,
      FJ ,
      FK ,
      FM ,
      FO ,
      FR ,
      GA ,
      GB ,
      GD ,
      GE ,
      GEAB ,
      GEOS ,
      GF ,
      GG ,
      GH ,
      GI ,
      GL ,
      GM ,
      GN ,
      GP ,
      GQ ,
      GR ,
      GS ,
      GT ,
      GU ,
      GW ,
      GY ,
      HK ,
      HM ,
      HN ,
      HR ,
      HT ,
      HU ,
      ID ,
      IE ,
      IL ,
      IM ,
      IN ,
      IO ,
      IQ ,
      IR ,
      IS ,
      IT ,
      JE ,
      JM ,
      JO ,
      JP ,
      KE ,
      KG ,
      KH ,
      KI ,
      KM ,
      KN ,
      KP ,
      KR ,
      KW ,
      KY ,
      KZ ,
      LA ,
      LB ,
      LC ,
      LI ,
      LK ,
      LR ,
      LS ,
      LT ,
      LU ,
      LV ,
      LY ,
      MA ,
      MC ,
      MD ,
      ME ,
      MF ,
      MG ,
      MH ,
      MK ,
      ML ,
      MM ,
      MN ,
      MO ,
      MP ,
      MQ ,
      MR ,
      MS ,
      MT ,
      MU ,
      MV ,
      MW ,
      MX ,
      MY ,
      MZ ,
      NA ,
      NC ,
      NE ,
      NF ,
      NG ,
      NI ,
      NL ,
      NO ,
      NP ,
      NR ,
      NU ,
      NZ ,
      OM ,
      PA ,
      PE ,
      PF ,
      PG ,
      PH ,
      PK ,
      PL ,
      PM ,
      PN ,
      PR ,
      PS ,
      PT ,
      PW ,
      PY ,
      QA ,
      RE ,
      RO ,
      RS ,
      RU ,
      RW ,
      SA ,
      SB ,
      SC ,
      SD ,
      SE ,
      SG ,
      SH ,
      SI ,
      SJ ,
      SK ,
      SL ,
      SM ,
      SN ,
      SO ,
      SR ,
      SS ,
      ST ,
      SV ,
      SX ,
      SY ,
      SZ ,
      TA ,
      TC ,
      TD ,
      TF ,
      TG ,
      TH ,
      TJ ,
      TK ,
      TL ,
      TM ,
      TN ,
      TO ,
      TR ,
      TT ,
      TV ,
      TW ,
      TZ ,
      UA ,
      UG ,
      UM ,
      US ,
      UY ,
      UZ ,
      VA ,
      VC ,
      VE ,
      VG ,
      VI ,
      VN ,
      VU ,
      WF ,
      WS ,
      XK ,
      YE ,
      YT ,
      ZA ,
      ZM ,
      ZW ,
} from "badrian-icon";


export const Icons = [
{ name: "AC", icon: AC },
{ name: "AD", icon: AD },
{ name: "AE", icon: AE },
{ name: "AF", icon: AF },
{ name: "AG", icon: AG },
{ name: "AI", icon: AI },
{ name: "AL", icon: AL },
{ name: "AM", icon: AM },
{ name: "AO", icon: AO },
{ name: "AQ", icon: AQ },
{ name: "AR", icon: AR },
{ name: "AS", icon: AS },
{ name: "AT", icon: AT },
{ name: "AU", icon: AU },
{ name: "AW", icon: AW },
{ name: "AX", icon: AX },
{ name: "AZ", icon: AZ },
{ name: "BA", icon: BA },
{ name: "BB", icon: BB },
{ name: "BD", icon: BD },
{ name: "BE", icon: BE },
{ name: "BF", icon: BF },
{ name: "BG", icon: BG },
{ name: "BH", icon: BH },
{ name: "BI", icon: BI },
{ name: "BJ", icon: BJ },
{ name: "BL", icon: BL },
{ name: "BM", icon: BM },
{ name: "BN", icon: BN },
{ name: "BO", icon: BO },
{ name: "BQ", icon: BQ },
{ name: "BR", icon: BR },
{ name: "BS", icon: BS },
{ name: "BT", icon: BT },
{ name: "BV", icon: BV },
{ name: "BW", icon: BW },
{ name: "BY", icon: BY },
{ name: "BZ", icon: BZ },
{ name: "CA", icon: CA },
{ name: "CC", icon: CC },
{ name: "CD", icon: CD },
{ name: "CF", icon: CF },
{ name: "CG", icon: CG },
{ name: "CH", icon: CH },
{ name: "CI", icon: CI },
{ name: "CK", icon: CK },
{ name: "CL", icon: CL },
{ name: "CM", icon: CM },
{ name: "CN", icon: CN },
{ name: "CO", icon: CO },
{ name: "CR", icon: CR },
{ name: "CU", icon: CU },
{ name: "CV", icon: CV },
{ name: "CW", icon: CW },
{ name: "CX", icon: CX },
{ name: "CY", icon: CY },
{ name: "CZ", icon: CZ },
{ name: "DE", icon: DE },
{ name: "DJ", icon: DJ },
{ name: "DK", icon: DK },
{ name: "DM", icon: DM },
{ name: "DO", icon: DO },
{ name: "DZ", icon: DZ },
{ name: "EC", icon: EC },
{ name: "EE", icon: EE },
{ name: "EG", icon: EG },
{ name: "EH", icon: EH },
{ name: "ER", icon: ER },
{ name: "ES", icon: ES },
{ name: "ET", icon: ET },
{ name: "EU", icon: EU },
{ name: "FI", icon: FI },
{ name: "FJ", icon: FJ },
{ name: "FK", icon: FK },
{ name: "FM", icon: FM },
{ name: "FO", icon: FO },
{ name: "FR", icon: FR },
{ name: "GA", icon: GA },
{ name: "GB", icon: GB },
{ name: "GD", icon: GD },
{ name: "GE", icon: GE },
{ name: "GEAB", icon: GEAB },
{ name: "GEOS", icon: GEOS },
{ name: "GF", icon: GF },
{ name: "GG", icon: GG },
{ name: "GH", icon: GH },
{ name: "GI", icon: GI },
{ name: "GL", icon: GL },
{ name: "GM", icon: GM },
{ name: "GN", icon: GN },
{ name: "GP", icon: GP },
{ name: "GQ", icon: GQ },
{ name: "GR", icon: GR },
{ name: "GS", icon: GS },
{ name: "GT", icon: GT },
{ name: "GU", icon: GU },
{ name: "GW", icon: GW },
{ name: "GY", icon: GY },
{ name: "HK", icon: HK },
{ name: "HM", icon: HM },
{ name: "HN", icon: HN },
{ name: "HR", icon: HR },
{ name: "HT", icon: HT },
{ name: "HU", icon: HU },
{ name: "ID", icon: ID },
{ name: "IE", icon: IE },
{ name: "IL", icon: IL },
{ name: "IM", icon: IM },
{ name: "IN", icon: IN },
{ name: "IO", icon: IO },
{ name: "IQ", icon: IQ },
{ name: "IR", icon: IR },
{ name: "IS", icon: IS },
{ name: "IT", icon: IT },
{ name: "JE", icon: JE },
{ name: "JM", icon: JM },
{ name: "JO", icon: JO },
{ name: "JP", icon: JP },
{ name: "KE", icon: KE },
{ name: "KG", icon: KG },
{ name: "KH", icon: KH },
{ name: "KI", icon: KI },
{ name: "KM", icon: KM },
{ name: "KN", icon: KN },
{ name: "KP", icon: KP },
{ name: "KR", icon: KR },
{ name: "KW", icon: KW },
{ name: "KY", icon: KY },
{ name: "KZ", icon: KZ },
{ name: "LA", icon: LA },
{ name: "LB", icon: LB },
{ name: "LC", icon: LC },
{ name: "LI", icon: LI },
{ name: "LK", icon: LK },
{ name: "LR", icon: LR },
{ name: "LS", icon: LS },
{ name: "LT", icon: LT },
{ name: "LU", icon: LU },
{ name: "LV", icon: LV },
{ name: "LY", icon: LY },
{ name: "MA", icon: MA },
{ name: "MC", icon: MC },
{ name: "MD", icon: MD },
{ name: "ME", icon: ME },
{ name: "MF", icon: MF },
{ name: "MG", icon: MG },
{ name: "MH", icon: MH },
{ name: "MK", icon: MK },
{ name: "ML", icon: ML },
{ name: "MM", icon: MM },
{ name: "MN", icon: MN },
{ name: "MO", icon: MO },
{ name: "MP", icon: MP },
{ name: "MQ", icon: MQ },
{ name: "MR", icon: MR },
{ name: "MS", icon: MS },
{ name: "MT", icon: MT },
{ name: "MU", icon: MU },
{ name: "MV", icon: MV },
{ name: "MW", icon: MW },
{ name: "MX", icon: MX },
{ name: "MY", icon: MY },
{ name: "MZ", icon: MZ },
{ name: "NA", icon: NA },
{ name: "NC", icon: NC },
{ name: "NE", icon: NE },
{ name: "NF", icon: NF },
{ name: "NG", icon: NG },
{ name: "NI", icon: NI },
{ name: "NL", icon: NL },
{ name: "NO", icon: NO },
{ name: "NP", icon: NP },
{ name: "NR", icon: NR },
{ name: "NU", icon: NU },
{ name: "NZ", icon: NZ },
{ name: "OM", icon: OM },
{ name: "PA", icon: PA },
{ name: "PE", icon: PE },
{ name: "PF", icon: PF },
{ name: "PG", icon: PG },
{ name: "PH", icon: PH },
{ name: "PK", icon: PK },
{ name: "PL", icon: PL },
{ name: "PM", icon: PM },
{ name: "PN", icon: PN },
{ name: "PR", icon: PR },
{ name: "PS", icon: PS },
{ name: "PT", icon: PT },
{ name: "PW", icon: PW },
{ name: "PY", icon: PY },
{ name: "QA", icon: QA },
{ name: "RE", icon: RE },
{ name: "RO", icon: RO },
{ name: "RS", icon: RS },
{ name: "RU", icon: RU },
{ name: "RW", icon: RW },
{ name: "SA", icon: SA },
{ name: "SB", icon: SB },
{ name: "SC", icon: SC },
{ name: "SD", icon: SD },
{ name: "SE", icon: SE },
{ name: "SG", icon: SG },
{ name: "SH", icon: SH },
{ name: "SI", icon: SI },
{ name: "SJ", icon: SJ },
{ name: "SK", icon: SK },
{ name: "SL", icon: SL },
{ name: "SM", icon: SM },
{ name: "SN", icon: SN },
{ name: "SO", icon: SO },
{ name: "SR", icon: SR },
{ name: "SS", icon: SS },
{ name: "ST", icon: ST },
{ name: "SV", icon: SV },
{ name: "SX", icon: SX },
{ name: "SY", icon: SY },
{ name: "SZ", icon: SZ },
{ name: "TA", icon: TA },
{ name: "TC", icon: TC },
{ name: "TD", icon: TD },
{ name: "TF", icon: TF },
{ name: "TG", icon: TG },
{ name: "TH", icon: TH },
{ name: "TJ", icon: TJ },
{ name: "TK", icon: TK },
{ name: "TL", icon: TL },
{ name: "TM", icon: TM },
{ name: "TN", icon: TN },
{ name: "TO", icon: TO },
{ name: "TR", icon: TR },
{ name: "TT", icon: TT },
{ name: "TV", icon: TV },
{ name: "TW", icon: TW },
{ name: "TZ", icon: TZ },
{ name: "UA", icon: UA },
{ name: "UG", icon: UG },
{ name: "UM", icon: UM },
{ name: "US", icon: US },
{ name: "UY", icon: UY },
{ name: "UZ", icon: UZ },
{ name: "VA", icon: VA },
{ name: "VC", icon: VC },
{ name: "VE", icon: VE },
{ name: "VG", icon: VG },
{ name: "VI", icon: VI },
{ name: "VN", icon: VN },
{ name: "VU", icon: VU },
{ name: "WF", icon: WF },
{ name: "WS", icon: WS },
{ name: "XK", icon: XK },
{ name: "YE", icon: YE },
{ name: "YT", icon: YT },
{ name: "ZA", icon: ZA },
{ name: "ZM", icon: ZM },
{ name: "ZW", icon: ZW },
];

//sosial

    
      //bendera
