import { 
    AdobeIllustrator, 
      AdobePhotoshop, 
      AdobeXD, 
      Aim, 
      Airbnb, 
      Allo, 
      Amazon, 
      Android, 
      Apple, 
      Atlassian, 
      Basecamp, 
      Behance, 
      Bing, 
      Bitbucket, 
      Bitcoin, 
      Bittorrent, 
      Blogger, 
      BuzzFeed, 
      Cloud, 
      Codeopen, 
      Confluence, 
      Coub, 
      Creativemarket, 
      Dailymotion, 
      Digg, 
      Discord, 
      Dribbble, 
      Dropbox, 
      DuckDuckGo, 
      Ethereum, 
      Evernote, 
      Facebook, 
      Fancy, 
      Figma, 
      Flickr, 
      Foursquare, 
      Framer, 
      Geo, 
      Github, 
      Googles, 
      Google, 
      GooglePlay, 
      Hola, 
      HTML5, 
      IE, 
      Instagram, 
      Intercom, 
      Invision, 
      Jira, 
      Kaixin001, 
      Kickstarter, 
      Line, 
      LinkedIN, 
      Love, 
      Mail, 
      MailChimp, 
      MailRu, 
      Marvel, 
      Mastercard, 
      Medium, 
      Messenger, 
      Mi, 
      Miliao, 
      Netflix, 
      Nintendo, 
      Notion, 
      OK, 
      Opera, 
      Outlook, 
      Patreon, 
      PayPal, 
      Periscope, 
      Phone, 
      Picassa, 
      Pinterest, 
      Pixate, 
      Playstation, 
      Pocket, 
      ProductHunt, 
      QQ, 
      Quora, 
      Reddit, 
      Renren, 
      RSS, 
      Share, 
      Shopify, 
      Shutterstock, 
      Sketch, 
      Skype, 
      Slack, 
      Snapchat, 
      Spotify, 
      Star, 
      Steam, 
      Strava, 
      StumbleUpon, 
      Taobao, 
      TeamViewer, 
      Telegram, 
      Tidal, 
      Tilda, 
      Tinder, 
      Tor, 
      Treehouse, 
      Trello, 
      Tripadvisor, 
      Tumblr, 
      Twitch, 
      Twitter, 
      Ubuntu, 
      Utorrent, 
      Viadeo, 
      Viber, 
      Vimeo, 
      Vine, 
      Visa, 
      VK, 
      Wechat, 
      Weibo, 
      WhatsApp, 
      WindowsCopy, 
      Wordpress, 
      World, 
      Xbox, 
      YandexBrowser, 
      Youtube, 
      Zerpply, 
      Zoom, 
      }
      from 'badrian-icon';
export const Icons = [
{ name: "AdobeIllustrator", icon: AdobeIllustrator },
{ name: "AdobePhotoshop", icon: AdobePhotoshop },
{ name: "AdobeXD", icon: AdobeXD },
{ name: "Aim", icon: Aim },
{ name: "Airbnb", icon: Airbnb },
{ name: "Allo", icon: Allo },
{ name: "Amazon", icon: Amazon },
{ name: "Android", icon: Android },
{ name: "Apple", icon: Apple },
{ name: "Atlassian", icon: Atlassian },
{ name: "Basecamp", icon: Basecamp },
{ name: "Behance", icon: Behance },
{ name: "Bing", icon: Bing },
{ name: "Bitbucket", icon: Bitbucket },
{ name: "Bitcoin", icon: Bitcoin },
{ name: "Bittorrent", icon: Bittorrent },
{ name: "Blogger", icon: Blogger },
{ name: "BuzzFeed", icon: BuzzFeed },
{ name: "Cloud", icon: Cloud },
{ name: "Codeopen", icon: Codeopen },
{ name: "Confluence", icon: Confluence },
{ name: "Coub", icon: Coub },
{ name: "Creativemarket", icon: Creativemarket },
{ name: "Dailymotion", icon: Dailymotion },
{ name: "Digg", icon: Digg },
{ name: "Discord", icon: Discord },
{ name: "Dribbble", icon: Dribbble },
{ name: "Dropbox", icon: Dropbox },
{ name: "DuckDuckGo", icon: DuckDuckGo },
{ name: "Ethereum", icon: Ethereum },
{ name: "Evernote", icon: Evernote },
{ name: "Facebook", icon: Facebook },
{ name: "Fancy", icon: Fancy },
{ name: "Figma", icon: Figma },
{ name: "Flickr", icon: Flickr },
{ name: "Foursquare", icon: Foursquare },
{ name: "Framer", icon: Framer },
{ name: "Geo", icon: Geo },
{ name: "Github", icon: Github },
{ name: "Googles", icon: Googles },
{ name: "Google", icon: Google },
{ name: "GooglePlay", icon: GooglePlay },
{ name: "Hola", icon: Hola },
{ name: "HTML5", icon: HTML5 },
{ name: "IE", icon: IE },
{ name: "Instagram", icon: Instagram },
{ name: "Intercom", icon: Intercom },
{ name: "Invision", icon: Invision },
{ name: "Jira", icon: Jira },
{ name: "Kaixin001", icon: Kaixin001 },
{ name: "Kickstarter", icon: Kickstarter },
{ name: "Line", icon: Line },
{ name: "LinkedIN", icon: LinkedIN },
{ name: "Love", icon: Love },
{ name: "Mail", icon: Mail },
{ name: "MailChimp", icon: MailChimp },
{ name: "MailRu", icon: MailRu },
{ name: "Marvel", icon: Marvel },
{ name: "Mastercard", icon: Mastercard },
{ name: "Medium", icon: Medium },
{ name: "Messenger", icon: Messenger },
{ name: "Mi", icon: Mi },
{ name: "Miliao", icon: Miliao },
{ name: "Netflix", icon: Netflix },
{ name: "Nintendo", icon: Nintendo },
{ name: "Notion", icon: Notion },
{ name: "OK", icon: OK },
{ name: "Opera", icon: Opera },
{ name: "Outlook", icon: Outlook },
{ name: "Patreon", icon: Patreon },
{ name: "PayPal", icon: PayPal },
{ name: "Periscope", icon: Periscope },
{ name: "Phone", icon: Phone },
{ name: "Picassa", icon: Picassa },
{ name: "Pinterest", icon: Pinterest },
{ name: "Pixate", icon: Pixate },
{ name: "Playstation", icon: Playstation },
{ name: "Pocket", icon: Pocket },
{ name: "ProductHunt", icon: ProductHunt },
{ name: "QQ", icon: QQ },
{ name: "Quora", icon: Quora },
{ name: "Reddit", icon: Reddit },
{ name: "Renren", icon: Renren },
{ name: "RSS", icon: RSS },
{ name: "Share", icon: Share },
{ name: "Shopify", icon: Shopify },
{ name: "Shutterstock", icon: Shutterstock },
{ name: "Sketch", icon: Sketch },
{ name: "Skype", icon: Skype },
{ name: "Slack", icon: Slack },
{ name: "Snapchat", icon: Snapchat },
{ name: "Spotify", icon: Spotify },
{ name: "Star", icon: Star },
{ name: "Steam", icon: Steam },
{ name: "Strava", icon: Strava },
{ name: "StumbleUpon", icon: StumbleUpon },
{ name: "Taobao", icon: Taobao },
{ name: "TeamViewer", icon: TeamViewer },
{ name: "Telegram", icon: Telegram },
{ name: "Tidal", icon: Tidal },
{ name: "Tilda", icon: Tilda },
{ name: "Tinder", icon: Tinder },
{ name: "Tor", icon: Tor },
{ name: "Treehouse", icon: Treehouse },
{ name: "Trello", icon: Trello },
{ name: "Tripadvisor", icon: Tripadvisor },
{ name: "Tumblr", icon: Tumblr },
{ name: "Twitch", icon: Twitch },
{ name: "Twitter", icon: Twitter },
{ name: "Ubuntu", icon: Ubuntu },
{ name: "Utorrent", icon: Utorrent },
{ name: "Viadeo", icon: Viadeo },
{ name: "Viber", icon: Viber },
{ name: "Vimeo", icon: Vimeo },
{ name: "Vine", icon: Vine },
{ name: "Visa", icon: Visa },
{ name: "VK", icon: VK },
{ name: "Wechat", icon: Wechat },
{ name: "Weibo", icon: Weibo },
{ name: "WhatsApp", icon: WhatsApp },
{ name: "WindowsCopy", icon: WindowsCopy },
{ name: "Wordpress", icon: Wordpress },
{ name: "World", icon: World },
{ name: "Xbox", icon: Xbox },
{ name: "YandexBrowser", icon: YandexBrowser },
{ name: "Youtube", icon: Youtube },
{ name: "Zerpply", icon: Zerpply },
{ name: "Zoom", icon: Zoom },
];